---
- name: Install packages
  hosts: all
  become: true
  tasks:
  
  - name: Install apache & vim
    ansible.builtin.package:
      name: 
        - "{{ apache_package }}"
        - vim

  - name: Start and enable apache
    ansible.builtin.service:
      name: "{{ apache_package }}"
      state: started
      enabled: true
    when: ansible_distribution == 'CentOS'

# No need to start and enable in Ubuntu

