---
- name: remove a package
  hosts: all
  become: true
  tasks:
  
  - name: Remove apache & vim
    ansible.builtin.yum:
      name: 
        - "{apache_package}"
        - vim
      state: absent

