---
- name: Update all servers
  hosts: all
  become: true
# pre_tasks will run first before any other tasks
  pre_tasks:
    
    - name: Update CentOS servers
      tags: always
      ansible.builtin.yum:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: Update Ubuntu servers
      tags: always
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- name: Configure webServers
  hosts: web_servers
  become: true
  tasks:
  
    - name: Install httpd & vim
      tags: apache,centos,httpd
      ansible.builtin.yum:
        name: 
          - httpd
          - vim
      when: ansible_distribution == 'CentOS'

    - name: Start and enable apache
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
      when: ansible_distribution == 'CentOS'

    - name: Install apache & vim
      tags: apache,ubuntu,apache2
      ansible.builtin.apt:
        name:
          - apache2
      when: ansible_distribution == 'Ubuntu'

# No need to start and enable in Ubuntu

- name: Install mariadb in db servers
  hosts: db_servers
  become: true
  tasks:
    
    - name: Install mariadb package (CentOS)
      tags: db,centos
      ansible.builtin.yum:
        name: 
          - mariadb
          - mariadb-server
        state: present
      ignore_errors: yes
      when: ansible_distribution == "CentOS"

    - name: Install mariadb package (Ubuntu)
      tags: db,ubuntu
      ansible.builtin.apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- name: Install samba in file servers
  tags: samba
  hosts: file_servers
  become: true
  tasks:
    - name: Install samba
      ansible.builtin.package:
        name: samba
        state: latest

#package module is used as both have same package name
